### ISSUE TITLE
Connection Error: Cannot assign requested address

### ISSUE THREAD

**Issue by totalhack** [qdrant/qdrant_client#105]
I am using langchain to test out qdrant. Langchain has a `from_texts` method shown [here](https://langchain.readthedocs.io/en/latest/_modules/langchain/vectorstores/qdrant.html#Qdrant) which makes the qdrant client connection and then tries to recreate a collection with `client.recreate_collection`. I stepped through the code and the initial connection works fine, but for some reason recreate_collection gets a "Cannot assign requested address" error. It doesn't appear the langchain code is wrong based on the qdrant examples I've seen.

I am running qdrant via docker compose, exposing port 6333. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 95, in send_inner
    response = self._client.send(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bhl_nlp/embeddings.py", line 51, in <module>
    qdrant = Qdrant.from_texts(
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/qdrant.py", line 190, in from_texts
    client.recreate_collection(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 1178, in recreate_collection
    self.delete_collection(collection_name)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 1116, in delete_collection
    return self.http.collections_api.delete_collection(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 658, in delete_collection
    return self._build_for_delete_collection(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api/collections_api.py", line 264, in _build_for_delete_collection
    return self.api_client.request(
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 68, in request
    return self.send(request, type_)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 85, in send
    response = self.middleware(request, self.send_inner)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 188, in __call__
    return call_next(request)
  File "/usr/local/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 97, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: [Errno 99] Cannot assign requested address
```

**Comment by totalhack** [comment]
Classic -- I needed host.docker.internal. I expected the connection attempt would have failed if something like that was wrong but apparently QdrantClient doesn't try to connect right away?

**Comment by neverho0d** [comment]
The issue is that Langchain's vector store object doesn't pass either Qdrant client or connection settings to the .from_text method, so it uses default settings which is http://localhost:6333. Fortunately, the .from_text method has its own connection parameters that should be used in case your server isn't on localhost.

**Comment by SandeepRongali** [comment]
I am running qdrant via cloud run in GCP. I am facing same error as like as above can you please help me to resolve it.
