### ISSUE TITLE
Container shutsdown automatically

### ISSUE THREAD

**Issue by ahmadmustafaanis** [qdrant/qdrant_client#13]
Hi, I installed qdrant on new os Ubuntu 18.04, and when I ran my previous code of searching, it starts giving me error.

As soon as I click on the execute on FastAPI docs, the container automatically shutdown. Overall output of container is 
```
(base) ahmad@ahmad:~$ sudo docker run -p 6333:6333   -v $(pwd)/qdrant_storage:/qdrant/storage   generall/qdrant
[sudo] password for ahmad: 
[2021-10-05T17:48:27Z INFO  wal::segment] Segment { path: "./storage/collections/reddit_videos/wal/open-2", entries: 0, space: (8/33554432) }: opened
[2021-10-05T17:48:27Z INFO  wal::segment] Segment { path: "./storage/collections/reddit_videos/wal/open-1", entries: 5, space: (824832/33554432) }: opened
[2021-10-05T17:48:27Z INFO  wal] Wal { path: "./storage/collections/reddit_videos/wal", segment-count: 1, entries: [0, 5)  }: opened
[2021-10-05T17:48:28Z INFO  qdrant] loaded collection: reddit_videos
[2021-10-05T17:48:28Z INFO  actix_server::builder] Starting 8 workers
[2021-10-05T17:48:28Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:6333" service on 0.0.0.0:6333
```

Error Message is
```python3
500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ahmad/Desktop/WortelAI/ElasticSearch/scripts/Qdrant_organized/QdrantServer/api.py", line 15, in search
    res = searcher.search(pos=text, neg=neg_text, subreddit=subreddit)
  File "/home/ahmad/Desktop/WortelAI/ElasticSearch/scripts/Qdrant_organized/QdrantServer/search.py", line 29, in search
    top=5,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_client/qdrant_client.py", line 224, in search
    params=search_params
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api/points_api.py", line 395, in search_points
    search_request=search_request,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api/points_api.py", line 248, in _build_for_search_points
    json=body,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 59, in request
    return self.send(request, type_)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 76, in send
    response = self.middleware(request, self.send_inner)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 179, in __call__
    return call_next(request)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 88, in send_inner
    raise ResponseHandlingException(e)
qdrant_openapi_client.exceptions.ResponseHandlingException: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

It does not even work on simple search or anything else. What can be the potential issue and fix.

**Comment by ahmadmustafaanis** [comment]
If I use it without FastAPI(on another task), then the error message is
```File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_sync/connection_pool.py", line 219, in request
    method, url, headers=headers, stream=stream, ext=ext
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 169, in _receive_event
    event = self.h11_state.next_event()
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 86, in send_inner
    response = self._client.send(request)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_client.py", line 772, in send
    history=[],
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_client.py", line 809, in _send_handling_auth
    history=history,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "updated/task2.py", line 48, in <module>
    searcher.search_text("MESSI")
  File "updated/task2.py", line 29, in search_text
    collection_name="reddit_videos", query_vector=text_features[0], top=5,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_client/qdrant_client.py", line 224, in search
    params=search_params
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api/points_api.py", line 395, in search_points
    search_request=search_request,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api/points_api.py", line 248, in _build_for_search_points
    json=body,
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 59, in request
    return self.send(request, type_)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 76, in send
    response = self.middleware(request, self.send_inner)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 179, in __call__
    return call_next(request)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_openapi_client/api_client.py", line 88, in send_inner
    raise ResponseHandlingException(e)
qdrant_openapi_client.exceptions.ResponseHandlingException: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```
And container closes automatically.

**Comment by generall** [comment]
Hi, it might be related to the issue https://github.com/qdrant/qdrant/issues/78 I am currently working on solution - temporary solution could be a manual build of the docker container on the target machine

**Comment by ahmadmustafaanis** [comment]
It was working fine in ubuntu 20.04, and I just copied it to new machine.

**Comment by ahmadmustafaanis** [comment]
Manual build solves the error. Thanks
