### ISSUE TITLE
qdrant_client.http.exceptions.ResponseHandlingException: timed out

### ISSUE THREAD

**Issue by ainilian** [qdrant/qdrant_client#138]
env
python 3.8.8
qdrant-client 1.1.0

codes:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

client = QdrantClient(host="7.223.133.58", port=6333)

client.create_collection(
    collection_name="my_collection111",
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)

error:
Traceback (most recent call last):
  File "D:/projects/code_search/test/rest_grpc_create.py", line 8, in <module>
    client.create_collection(
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\qdrant_client.py", line 1729, in create_collection
    result: Optional[bool] = self.http.collections_api.create_collection(
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api\collections_api.py", line 754, in create_collection
    return self._build_for_create_collection(
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api\collections_api.py", line 194, in _build_for_create_collection
    return self.api_client.request(
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api_client.py", line 68, in request
    return self.send(request, type_)
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api_client.py", line 85, in send
    response = self.middleware(request, self.send_inner)
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api_client.py", line 188, in __call__
    return call_next(request)
  File "D:\software\anaconda3\envs\torch7\lib\site-packages\qdrant_client\http\api_client.py", line 97, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: timed out

**Comment by ainilian** [comment]
Used postman
PUT http://7.223.133.58:6333/collections/my_collection111
Body->raw->JSON: {"vectors": {"size": 100, "distance": "Cosine"}}

reponse:
{
    "result": true,
    "status": "ok",
    "time": 10.190639613
}

I think it is working on Qdrant server.

**Comment by ainilian** [comment]
Hi @generall 
I have tried the method follow [issues 21#](https://github.com/qdrant/qdrant_client/issues/21#issuecomment-1053792067).
It didn't work.

**Comment by ainilian** [comment]
http of qdrant_client use the 'httpx' package.
I tried three package to request: httpx, aiohttp, requests.

example of requests worked well:
------------------------------------------
import uuid
import numpy as np
import requests
data = {"points": [{
            "id": str(uuid.uuid1()),
            "vector": np.random.uniform(-10, 10, 100).tolist()
        }]}
url = 'http://7.223.133.58:6333/collections/my_collection111/points'
resp = requests.put(url, json=data).json()
-------------------------------------------

example of aiohttp worked well:
-------------------------------
url = 'http://7.223.133.58:6333/collections/my_collection111/points'
data = {"points": [{
            "id": str(uuid.uuid1()),
            "vector": np.random.uniform(-10, 10, 100).tolist()
        }]}
async def main():
    async with aiohttp.ClientSession() as client:
        async with client.put(url, json=data) as resp:
            result = await resp.json()
            print(result)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
------------------------------------

but eaxmple of httpx failed:
--------------------------------------------------
data = {"points": [{
            "id": str(uuid.uuid1()),
            "vector": np.random.uniform(-10, 10, 100).tolist()
        }]}
url = 'http://7.223.133.58:6333/collections/my_collection111/points'
import httpx
resp = httpx.put(url, json=data, timeout=httpx.Timeout(timeout=20))
-----------------------------------
<Response [504 Gateway Time-out]>

Composied with other packages, Only httpx supported http/2 protocol. Does this have anything to do with that? Looking forward to your reply.
@generall

**Comment by generall** [comment]
hi @ainilian, could you please try to reproduce it with disabled http2 in httpx?

**Comment by ainilian** [comment]
> hi @ainilian, could you please try to reproduce it with disabled http2 in httpx?

Hi @generall, I have tried to reproduce it with enabled http1 and enabled http2 in httpx. The results are same and puzzling.

enabled http1:
```python
import httpx
from httpx._client import Client

url = 'http://7.223.133.58:6333/collections/my_collection111/cluster'
with Client(
        http1=True,
        http2=False,
        timeout=httpx.Timeout(timeout=10.0),
) as client:
    resp = client.request(
        method='GET',
        url=url,
    )
print(resp.http_version), print(resp)
```
response:
HTTP/1.1
<Response [504 Gateway Time-out]>

enabled http2:
```python
import httpx
from httpx._client import Client
url = 'http://7.223.133.58:6333/collections/my_collection111/cluster'

with Client(
        http1=False,
        http2=True,
        timeout=httpx.Timeout(timeout=10.0),
) as client:
    resp = client.request(
        method='GET',
        url=url
    )
print(resp.http_version), print(resp)
```
response
HTTP/1.1
<Response [504 Gateway Time-out]>

**Comment by generall** [comment]
that's very strange, could you please describe your setup, so we could try to reproduce that? Where do you host qdrant, is there any proxies in between?

**Comment by ainilian** [comment]
The bug is caused by the proxy. When I close the proxy, it works.

**Comment by wuQi-666** [comment]
when i use qdrant_client to insert data into collection ,i meet qdrant_client.http.exceptions.ResponseHandingException:time out. The solution to the problem is  The reason for this issue may be that there is a limit to the number of data inserted by qdrant at once. My solution is to insert every 1000 pieces into it. Write this if statement into the for loop.
            if index % 1000 == 0:
                points["ids"] = ids
                points["payloads"] = payloads
                points["vectors"] = vectors
                # 然后调用方法往表中插入数据
                qdrant.insert_point(collection_name, points)

**Comment by liebkne** [comment]
Even I set a super small batch size (200), I still get timed out error in a high performance server. How to debug this?
