### ISSUE TITLE
Json deserialize error: when used client.search()

### ISSUE THREAD

**Issue by sainivedh19pt** [qdrant/qdrant_client#51]
`
def get_filter2(img_filerns):

    filter_rn = lambda filern: FieldCondition(
                key='file_rn',  # Condition based on values of `rand_number` field.
                match=models.MatchValue(value=filern)
            )
        
    type_filter = Filter(should = [filter_rn(filern) for filern in img_filerns])
    return type_filter
`
results = client.search(collection_name="search_test",
            query_vector=vectors_q.flatten(),
            query_filter=filters,
            limit=2 
        )
print(results)
`

`
Traceback (most recent call last):
  File ".\qdrant_search.py", line 74, in <module>      
    search_vectors()
  File ".\qdrant_search.py", line 69, in search_vectors
    limit=2  # 5 the most closest results is enough
  File "C:\Users\qdrant_client\qdrant_client.py", line 251, in search
    score_threshold=score_threshold
  File "C:\Users\qdrant_client\http\api\points_api.py", line 654, in search_points
    search_request=search_request,
  File "C:\Users\qdrant_client\http\api\points_api.py", line 344, in _build_for_search_points
    json=body,
  File "C:\Users\qdrant_client\http\api_client.py", line 62, in request
    return self.send(request, type_)
  File "C:\Users\qdrant_client\http\api_client.py", line 85, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 422 (Unprocessable Entity)
Raw response content:
b'{"result":null,"status":{"error":"Json deserialize error: missing field `top` at line 1 column 10879"},"time":0.0}'
`

> Qdrant-client==0.8.4
> Search used to work with qdrant-client==0.8.0 using older filter condition given below

`def get_filter(img_filerns):

    filter_rn = lambda filern: {
            "key": "file_rn",  
            "match": { # This condition checks if payload field have requested value
                "keyword": filern
            }
        }

    # Define a filter for cities
    type_filter = Filter(**{
        "should": [filter_rn(filern) for filern in img_filerns]
    })

    return type_filter
`

Please let me know if anymore details are required

Thanks

**Comment by sainivedh19pt** [comment]
Oops. Realised the qdrant docker is not the latest one. 
The search api is working fine with latest qdocker image - 0.8.4

Thanks
