### ISSUE TITLE
validation error for SearchRequest vector -> 0

### ISSUE THREAD

**Issue by ahmadmustafaanis** [qdrant/qdrant_client#8]
I followed the neural search tutorial given on the website. I used CLIP by OpenAI for text embeddings. and uploaded them to qdrant via
 ```python3
self.qdrant_client.upload_collection(
            collection_name=self.collection_name,
            vectors=self.vectors,
            payload=self.payload,
            ids=ids,  # Vector ids will be assigned automatically if None
            batch_size=batch_size,
        )
```
vectors are my embeddings and there size is `1,768`. Now When I want to make a search API, following the tutorial, this is my code.
```
def search(self, text: str):
        self.model.descriptions = text
        # Convert text query into vector
        self.model.get_text_tokens() # tokenized the text
        vector = self.model.get_text_embeddings().detach().cpu().numpy() # torch tensor to numpy

        assert type(vector) == np.ndarray, "Embeddings should be in numpy"

        assert vector.shape == (1, 768), "wrong shape"

        # Use `vector` for search for closest vectors in the collection
        search_result = self.qdrant_client.search(
            collection_name=self.collection_name,
            query_vector=vector,
            query_filter=None,  # We don't want any filters for now
            top=5,  # 5 the most closest results is enough
        )

        # `search_result` contains found vector ids with similarity scores along with the stored payload
        # In this function we are interested in payload only
        payloads = [payload for point, payload in search_result]
        return payloads
```
Now If I run this function, or call it via FastAPI, the code for FastAPI is 

```
from fastapi import FastAPI

# That is the file where NeuralSearcher is stored
from search import NeuralSearcher

app = FastAPI()

collection_name = "my_collection"

searcher = NeuralSearcher(collection_name=collection_name)


@app.get("/api/search")
def search(text: str):
    res = searcher.search(text=text)
    return {"result": res}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
```
Now If I run the search function, or call it via FastAPI, I get the following error.

```
INFO:     127.0.0.1:34974 - "GET /api/search?text=messi HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ahmad/Desktop/WortelAI/ElasticSearch/scripts/VC_FINAL/QdrantServer/api.py", line 15, in search
    res = searcher.search(text=text)
  File "/home/ahmad/Desktop/WortelAI/ElasticSearch/scripts/VC_FINAL/QdrantServer/search.py", line 31, in search
    top=5,  # 5 the most closest results is enough
  File "/home/ahmad/anaconda3/envs/new_youtube/lib/python3.7/site-packages/qdrant_client/qdrant_client.py", line 224, in search
    params=search_params
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SearchRequest
vector -> 0
  value is not a valid float (type=type_error.float)
```
I have no idea why is this error, or what does it means. Please help.

**Comment by ahmadmustafaanis** [comment]
The output of `http://0.0.0.0:6333/collections/my_collection` is 

```
"result":{"status":"green","vectors_count":56,"segments_count":5,"disk_data_size":0,"ram_data_size":0,"config":{"params":{"vector_size":768,"distance":"Dot"},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"max_segment_number":5,"memmap_threshold":50000,"indexing_threshold":20000,"payload_indexing_threshold":10000,"flush_interval_sec":10},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0}},"payload_schema":{"author_name":{"data_type":{"type":"keyword"},"indexed":false},"title":{"data_type":{"type":"keyword"},"indexed":false},"video_id":{"data_type":{"type":"integer"},"indexed":false},"domain":{"data_type":{"type":"keyword"},"indexed":false},"selftext":{"data_type":{"type":"keyword"},"indexed":false},"author_fullname":{"data_type":{"type":"keyword"},"indexed":false},"thumbnail_title":{"data_type":{"type":"keyword"},"indexed":false},"url":{"data_type":{"type":"keyword"},"indexed":false},"subreddit":{"data_type":{"type":"keyword"},"indexed":false}}},"status":"ok","time":0.000464495}
```

**Comment by generall** [comment]
Hi @ahmadmustafaanis, 
> `assert vector.shape == (1, 768), "wrong shape"`
search function actually expects 1D vector.

Can you please try
```
search_result = self.qdrant_client.search(
            collection_name=self.collection_name,
            query_vector=vector[0],
            query_filter=None,  # We don't want any filters for now
            top=5,  # 5 the most closest results is enough
        )
```

**Comment by ahmadmustafaanis** [comment]
Thanks. It is working now.
